// Generated by CoffeeScript 1.6.1
(function() {
  var Channel, async, _;

  _ = require("underscore");

  async = require("async");

  Channel = (function() {

    Channel.prototype.id = void 0;

    Channel.prototype.subscribers = void 0;

    function Channel(p_id) {
      this.id = p_id;
      this.subscribers = [];
    }

    Channel.prototype.addSubscriber = function(newsub) {
      _.each(this.subscribers, function(sub) {
        if (sub.barename === newsub.barename) {
          sub.addFriend(newsub.fullname);
          return newsub.addFriend(sub.fullname);
        }
      });
      return this.subscribers.push(newsub);
    };

    Channel.prototype.publish = function(msg) {
      return this.send(msg);
    };

    Channel.prototype.send = function(msg) {
      var _this = this;
      return async.each(this.subscribers, function(sub) {
        sub.onMessage(msg);
        return function(err) {};
      });
    };

    return Channel;

  })();

  exports.Channel = Channel;

}).call(this);
