// Generated by CoffeeScript 1.6.1
(function() {
  var HashRing, Master, _;

  HashRing = require("hashring");

  _ = require("underscore");

  Master = (function() {

    Master.prototype.ring = void 0;

    Master.prototype.workers = void 0;

    function Master() {
      this.ring = new HashRing();
      this.workers = [];
    }

    Master.prototype.addWorker = function(worker) {
      this.ring.add(worker.id);
      return this.workers.push(worker);
    };

    Master.prototype.send = function(msg) {
      var worker, workerID;
      workerID = this.ring.get(msg);
      worker = _.find(this.workers, function(w) {
        return w.id === workerID;
      });
      return worker.onMessage(msg);
    };

    return Master;

  })();

  exports.Master = Master;

}).call(this);
