// Generated by CoffeeScript 1.6.1
(function() {
  var Publisher, async, _;

  _ = require("underscore");

  async = require("async");

  Publisher = (function() {

    Publisher.prototype.channels = void 0;

    function Publisher() {
      this.channels = [];
    }

    Publisher.prototype.addChannel = function(newch) {
      return this.channels.push(newch);
    };

    Publisher.prototype.send = function(msg) {
      var _this = this;
      return async.each(this.channels, function(ch) {
        ch.publish(msg);
        return function(err) {};
      });
    };

    return Publisher;

  })();

  exports.Publisher = Publisher;

}).call(this);
