// Generated by CoffeeScript 1.6.1
(function() {
  var Slave;

  Slave = (function() {

    Slave.prototype.id = void 0;

    Slave.prototype.msgCount = void 0;

    function Slave(p_id) {
      this.id = p_id;
      this.msgCount = 0;
    }

    Slave.prototype.onMessage = function(message) {
      console.log("" + this.id + " PROCESSING msg '" + message + "'");
      return this.msgCount++;
    };

    return Slave;

  })();

  exports.Slave = Slave;

}).call(this);
