// Generated by CoffeeScript 1.6.1
(function() {
  var HashRing, Peer, Subscriber,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  HashRing = require("hashring");

  Peer = require("./peer").Peer;

  Subscriber = (function(_super) {

    __extends(Subscriber, _super);

    Subscriber.prototype.ring = void 0;

    Subscriber.prototype.msgCount = void 0;

    function Subscriber(p_barename) {
      Subscriber.__super__.constructor.call(this, p_barename);
      this.ring = new HashRing(this.fullname);
      this.msgCount = 0;
    }

    Subscriber.prototype.subscribe = function(channel) {
      return channel.addSubscriber(this);
    };

    Subscriber.prototype.addFriend = function(friendId) {
      return this.ring.add(friendId);
    };

    Subscriber.prototype.removeFriend = function(friendId) {
      return this.ring.remove(friendId);
    };

    Subscriber.prototype.onMessage = function(message) {
      if (this.fullname === this.ring.get(message)) {
        console.log("'" + message + "' processed by " + this.fullname);
        return this.msgCount++;
      }
    };

    return Subscriber;

  })(Peer);

  exports.Subscriber = Subscriber;

}).call(this);
