// Generated by CoffeeScript 1.6.1
(function() {
  var Channel, Master, Publisher, Slave, Subscriber, main;

  Master = require("../lib/master").Master;

  Slave = require("../lib/slave").Slave;

  Publisher = require("../lib/publisher").Publisher;

  Channel = require("../lib/channel").Channel;

  Subscriber = require("../lib/subscriber").Subscriber;

  main = function() {
    var channel, msgCount, publisher, _results;
    channel = new Channel("CH1");
    (new Subscriber("SUB1")).subscribe(channel);
    (new Subscriber("SUB1")).subscribe(channel);
    (new Subscriber("SUB2")).subscribe(channel);
    publisher = new Publisher();
    publisher.addChannel(channel);
    msgCount = 21;
    _results = [];
    while (msgCount -= 1) {
      _results.push(publisher.send("msg " + msgCount));
    }
    return _results;
  };

  main();

}).call(this);
